export const expertsData = [
  {
    name: "Aarav Sharma",
    role: "Dietitian",
    spec: "Weight Loss",
    clients: 18,
    maxlimit: 25,
    rating: 4.7,
    responseTime: "1 hr",
    status: "Active",
  },
  {
    name: "Meera Nair",
    role: "Trainer",
    spec: "Strength Training",
    clients: 22,
    maxlimit: 30,
    rating: 4.8,
    responseTime: "45 min",
    status: "Active",
  },
  {
    name: "Rohan Gupta",
    role: "Therapist",
    spec: "Mental Wellness",
    clients: 12,
    maxlimit: 20,
    rating: 4.5,
    responseTime: "2 hrs",
    status: "Active",
  },
  {
    name: "Neha Verma",
    role: "Dietitian",
    spec: "Diabetes Management",
    clients: 10,
    maxlimit: 18,
    rating: 4.6,
    responseTime: "1.5 hrs",
    status: "Inactive",
  },
  {
    name: "Vikram Singh",
    role: "Trainer",
    spec: "Yoga & Mobility",
    clients: 15,
    maxlimit: 25,
    rating: 4.9,
    responseTime: "30 min",
    status: "Active",
  },
  {
    name: "Kavya Iyer",
    role: "Therapist",
    spec: "Stress Relief",
    clients: 8,
    maxlimit: 15,
    rating: 4.4,
    responseTime: "3 hrs",
    status: "Suspended",
  },
  {
    name: "Arjun Reddy",
    role: "Dietitian",
    spec: "Muscle Gain Nutrition",
    clients: 14,
    maxlimit: 25,
    rating: 4.3,
    responseTime: "2 hrs",
    status: "Active",
  },
  {
    name: "Sanya Kapoor",
    role: "Trainer",
    spec: "HIIT & Cardio",
    clients: 20,
    maxlimit: 28,
    rating: 4.6,
    responseTime: "1 hr",
    status: "Inactive",
  },
  {
    name: "Dr. Mahesh Rao",
    role: "Therapist",
    spec: "Rehabilitation",
    clients: 6,
    maxlimit: 12,
    rating: 4.9,
    responseTime: "50 min",
    status: "Active",
  },
  {
    name: "Tara Desai",
    role: "Dietitian",
    spec: "PCOS Nutrition",
    clients: 16,
    maxlimit: 22,
    rating: 4.8,
    responseTime: "1 hr",
    status: "Active",
  },
];
