export const  clientsData = [
  {
    client: "Aarav Kumar",
    program: "Weight Loss",
    duration: "60 Days",
    experts: ["Dietitian", "Trainer", "Therapist"],
    start: "02 Jan 2025",
    end: "03 Mar 2025",
    compliance: "78%",
    status: "Active",
  },
  {
    client: "Vikram Singh",
    program: "Diabetes",
    duration: "30 Days",
    experts: ["Dietitian"],
    start: "20 Jan 2025",
    end: "20 Feb 2025",
    compliance: "69%",
    status: "Active",
  },
  {
    client: "Sonali Jain",
    program: "Fitness Toning",
    duration: "30 Days",
    experts: ["Dietitian", "Therapist"],
    start: "10 Dec 2024",
    end: "10 Feb 2025",
    compliance: "74%",
    status: "Inactive",
  },
  {
    client: "Rohan Mehta",
    program: "PCOD Management",
    duration: "45 Days",
    experts: ["Dietitian"],
    start: "12 Jan 2025",
    end: "26 Feb 2025",
    compliance: "82%",
    status: "Active",
  },
  {
    client: "Lakshmi Nair",
    program: "Postpartum Weight Loss",
    duration: "75 Days",
    experts: ["Dietitian", "Trainer"],
    start: "05 Nov 2024",
    end: "19 Jan 2025",
    compliance: "88%",
    status: "Suspended",
  },
  {
    client: "Harish Kumar",
    program: "Cholesterol Control",
    duration: "40 Days",
    experts: ["Dietitian"],
    start: "01 Jan 2025",
    end: "10 Feb 2025",
    compliance: "63%",
    status: "Inactive",
  },
  {
    client: "Priya Sharma",
    program: "Yoga Therapy",
    duration: "60 Days",
    experts: ["Therapist"],
    start: "15 Dec 2024",
    end: "13 Feb 2025",
    compliance: "91%",
    status: "Active",
  },
  {
    client: "Arjun Patel",
    program: "Muscle Gain",
    duration: "90 Days",
    experts: ["Trainer"],
    start: "20 Nov 2024",
    end: "18 Feb 2025",
    compliance: "76%",
    status: "Active",
  },
  {
    client: "Nidhi Gupta",
    program: "Stress Management",
    duration: "30 Days",
    experts: ["Therapist"],
    start: "02 Jan 2025",
    end: "01 Feb 2025",
    compliance: "80%",
    status: "Active",
  },
  {
    client: "Amaan Qureshi",
    program: "Thyroid Management",
    duration: "60 Days",
    experts: ["Dietitian"],
    start: "18 Dec 2024",
    end: "20 Feb 2025",
    compliance: "72%",
    status: "Inactive",
  },
  {
    client: "Simran Kaur",
    program: "Body Toning",
    duration: "45 Days",
    experts: ["Trainer"],
    start: "07 Jan 2025",
    end: "21 Feb 2025",
    compliance: "95%",
    status: "Active",
  },
  {
    client: "Mahesh Reddy",
    program: "Back Pain Relief",
    duration: "30 Days",
    experts: ["Therapist"],
    start: "03 Jan 2025",
    end: "02 Feb 2025",
    compliance: "68%",
    status: "Suspended",
  },
  {
    client: "Sneha Desai",
    program: "Cardio Fitness",
    duration: "60 Days",
    experts: ["Trainer"],
    start: "12 Dec 2024",
    end: "10 Feb 2025",
    compliance: "89%",
    status: "Active",
  },
];
