export const financeData = [
  {
    name: "Aarav Sharma",
    role: "Dietitian",
    baseSalary: 70000,
    incentive: 18000,
    totalPayout: 88000,
    rating: 4.7,
    responseTime: "1 hr",
    status: "Active",
  },
  {
    name: "Meera Nair",
    role: "Trainer",
    baseSalary: 60000,
    incentive: 14000,
    totalPayout: 74000,
    rating: 4.8,
    responseTime: "45 min",
    status: "Active",
  },
  {
    name: "Rohan Gupta",
    role: "Therapist",
    baseSalary: 50000,
    incentive: 10000,
    totalPayout: 60000,
    rating: 4.5,
    responseTime: "2 hrs",
    status: "Active",
  },
  {
    name: "Neha Verma",
    role: "Dietitian",
    baseSalary: 60000,
    incentive: 9000,
    totalPayout: 69000,
    rating: 4.6,
    responseTime: "1.5 hrs",
    status: "Inactive",
  },
  {
    name: "Vikram Singh",
    role: "Trainer",
    baseSalary: 70000,
    incentive: 18000,
    totalPayout: 88000,
    rating: 4.9,
    responseTime: "30 min",
    status: "Active",
  },
  {
    name: "Kavya Iyer",
    role: "Therapist",
    baseSalary: 50000,
    incentive: 8000,
    totalPayout: 58000,
    rating: 4.4,
    responseTime: "3 hrs",
    status: "Suspended",
  },
  {
    name: "Arjun Reddy",
    role: "Dietitian",
    baseSalary: 60000,
    incentive: 9000,
    totalPayout: 69000,
    rating: 4.3,
    responseTime: "2 hrs",
    status: "Active",
  },
  {
    name: "Sanya Kapoor",
    role: "Trainer",
    baseSalary: 60000,
    incentive: 12000,
    totalPayout: 72000,
    rating: 4.6,
    responseTime: "1 hr",
    status: "Inactive",
  },
  {
    name: "Dr. Mahesh Rao",
    role: "Therapist",
    baseSalary: 70000,
    incentive: 18000,
    totalPayout: 88000,
    rating: 4.9,
    responseTime: "50 min",
    status: "Active",
  },
  {
    name: "Tara Desai",
    role: "Dietitian",
    baseSalary: 60000,
    incentive: 14000,
    totalPayout: 74000,
    rating: 4.8,
    responseTime: "1 hr",
    status: "Active",
  },
];
